sudo: required
services: 
  - docker
before_install:
  - docker build -t batoucheoussama/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true USERNAME/react-test npm test

after_success:
  - docker build batoucheoussama/multi-client ./client
  - docker build batoucheoussama/multi-nginx ./nginx
  - docker build batoucheoussama/multi-server ./server
  - docker build batoucheoussama/multi-worker ./worker
  #log in the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #take those images and push them to docker hub
  - docker push batoucheoussama/multi-client
  - docker push batoucheoussama/multi-nginx
  - docker push batoucheoussama/multi-server
  - docker push batoucheoussama/multi-worker